# -*- coding: utf-8 -*-
"""Copia_de_Clase_8_08_de_septiembre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18AtbSOVRGX2PfSXinufA1-wzl_LjQEJq
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A : ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR : DANNA ISABELLA RUEDA MARÍN**
#**GRADO DÉCIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?**
# Python es un lenguaje de programación flexible y diseñado para ser fácil de leer. Es un lenguaje orientado a objetos y de alto nivel. Gracias a su sintaxis sencilla es un muy buen lenguaje para aprender a programar. Python utiliza módulos y paquetes lo cual fomenta la modularidad y la reutilización de código.

#**Fecha de lanzamiento**: 1991

#**Creadores**:Guido Van Rossum

#**Recuperado de:**https://datademia.es/blog/que-es-python
"""

print("Esto es una suma")
numero_uno= 52
numero_dos= 9
resultado= numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno= 19
numero_dos= 13
resultado= numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicación")
numero_uno= 47
numero_dos= 9
resultado= numero_uno * numero_dos
print(resultado)

print("Esto es una división")
numero_uno= 80
numero_dos= 4
resultado= numero_uno / numero_dos
print(resultado)

"""#**Ejercicios de Tipos de Datos Simples**

## Ejercicio 1

Escribe un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla en líneas distintas el nombre del usuario tantas veces como el número introducido.
"""

nombre = input("¿Cómo te llamas?") 
 n = input("Introduce un número entero:")
print((nombre + "\n") * int(n))

"""## Ejercicio 2
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tu índice de masa corporal es <imc>' donde '<imc>' es el índice de masa corporal calculado redondeado con dos decimales.  
"""

peso = input("¿cuál es tu peso en kg?")
estatura = input("¿cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("tu índice de masa corporal es" + str(imc))

"""# **LIBRERÍAS EN PHYTON**

"""